version: '3.8'

services:
  store-service:
    build:
      dockerfile: Dockerfile
    container_name: store-service
    environment:
      SPRING_DATA_REDIS_HOST: redis
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - store-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - store-network

networks:
  store-network:

volumes:
  redis-data: