spring:
  application:
    name: store
  datasource:
    url: jdbc:h2:mem:store
    driver-class-name: org.h2.Driver
    username: store
    password: store1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
